# Generated by Django 4.2.4 on 2024-02-01 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logintbl',
            old_name='type',
            new_name='usertype',
        ),
    ]
