# Generated by Django 4.2.4 on 2024-02-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0003_registrationbaker_bakerid_registrationuser_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCakes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=25)),
                ('desc', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
            ],
        ),
    ]
