# Generated by Django 4.2.4 on 2024-02-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0004_addcakes'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcakes',
            name='bakerid',
            field=models.IntegerField(null=True),
        ),
    ]
