# Generated by Django 4.2.4 on 2024-02-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0005_addcakes_bakerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavour', models.CharField(max_length=25)),
                ('desc', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('quantity', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='addcakes',
            name='quantity',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
