# Generated by Django 4.2.4 on 2024-02-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0007_remove_addcakes_bakerid_request_bakerid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(default='pending', max_length=20, null=True),
        ),
    ]
