# Generated by Django 4.2.4 on 2024-02-08 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0008_request_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=500)),
                ('current_date', models.DateField()),
                ('status', models.CharField(default='Processing', max_length=25)),
                ('bakerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cakes.registrationbaker')),
                ('cakeId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cakes.addcakes')),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cakes.registrationuser')),
            ],
        ),
    ]
