# Generated by Django 4.2.4 on 2024-02-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0009_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('current_date', models.DateField()),
            ],
        ),
    ]
