# Generated by Django 4.2.4 on 2024-02-12 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0010_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bookingId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cakes.booking'),
        ),
    ]
