# Generated by Django 4.2.4 on 2024-02-13 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0012_payment_status_alter_booking_current_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(default='booking confirmed', max_length=25),
        ),
    ]
