# Generated by Django 4.2.4 on 2024-02-13 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0013_alter_booking_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='bookingId',
            new_name='userId',
        ),
        migrations.AddField(
            model_name='payment',
            name='cakeId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cakes.addcakes'),
        ),
    ]
