# Generated by Django 4.2.4 on 2024-02-13 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0014_rename_bookingid_payment_userid_payment_cakeid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='cakeId',
        ),
    ]
