# Generated by Django 4.2.4 on 2024-02-13 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0015_remove_payment_cakeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cakes.registrationuser'),
        ),
    ]
