# Generated by Django 4.2.4 on 2024-02-13 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0016_alter_payment_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('feedback', models.CharField(max_length=250)),
                ('rating', models.IntegerField(null=True)),
                ('current_date', models.DateField(null=True)),
                ('bookId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cakes.booking')),
            ],
        ),
    ]
