# Generated by Django 4.2.4 on 2024-02-16 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0017_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('bookId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cakes.booking')),
                ('requestId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cakes.request')),
            ],
        ),
    ]
